# Generated by Django 6.0.1 on 2026-01-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_type_issue_issue_type_alter_issue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_type',
            field=models.CharField(choices=[('BUG', 'Bug'), ('AMELIORATION', 'amelioration'), ('Tache', 'tache')], max_length=20),
        ),
    ]
